### ISSUE TITLE
docker config

### ISSUE THREAD

**Issue by kalmike** [ferr4n/multicoin#1]

**Comment by kalmike** [comment]
solved

**Comment by ferr4n** [comment]
Thanks for the question, apps should be up and running just after
installation, I'm clarifying it in the next version of read.me file and
script (more apps are being added too!).

El dl., 4 de març 2024, 8:13, kalmike ***@***.***> va
escriure:

**Comment by ferr4n** [comment]
Done, version 1.5.1 is out with several corrections and one more coin: Meson
